name: Deploy website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create zip file of www directory
      run: zip -r html.zip www

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy zip file to webserver tmp directory
      run: scp -o StrictHostKeyChecking=no html.zip ec2-user@${{ secrets.EC2_PUB_IP }}:/tmp/

    - name: Unzip and deploy files within Nginx
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUB_IP }} << 'EOF'
          sudo rm -r /usr/share/nginx/html_old/
          sudo mv /usr/share/nginx/html/ /usr/share/nginx/html_old/
          sudo unzip -o /tmp/html.zip -d /usr/share/nginx/
          sudo mv /usr/share/nginx/www/ /usr/share/nginx/html/
          sudo rm /tmp/html.zip
          sudo systemctl restart nginx
        EOF