name: Deploy website

on:
  push:
    branches:
      - main
    paths:
      - 'www/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      WEB_SSH_SG_ID: ${{ secrets.WEB_SSH_SG_ID }}

    steps:
    - name: Set AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-2
    
    - name: Get GitHub runner IP address
      id: ip
      uses: haythem/public-ip@v1.2

    - name: Whitelist GitHub runner IP address
      run: |
        aws ec2 authorize-security-group-ingress \
          --group-id $WEB_SSH_SG_ID \
          --protocol tcp \
          --port 22 \
          --cidr ${{ steps.ip.outputs.ipv4 }}/32

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create zip file of www directory
      run: zip -r html.zip www

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy zip file to webserver /tmp/ directory
      run: scp -o StrictHostKeyChecking=no html.zip ec2-user@${{ secrets.EC2_PUB_IP }}:/tmp/

    - name: Unzip and deploy files within Nginx
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUB_IP }} << 'EOF'
          sudo rm -r /usr/share/nginx/html_old/
          sudo mv /usr/share/nginx/html/ /usr/share/nginx/html_old/
          sudo unzip -o /tmp/html.zip -d /usr/share/nginx/
          sudo mv /usr/share/nginx/www/ /usr/share/nginx/html/
          sudo rm /tmp/html.zip
          sudo systemctl restart nginx
        EOF

    - name: Revoke GitHub runner IP address
      run: |
        aws ec2 revoke-security-group-ingress \
          --group-id $WEB_SSH_SG_ID \
          --protocol tcp \
          --port 22 \
          --cidr ${{ steps.ip.outputs.ipv4 }}/32

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: 'release-${{ github.sha }}'
        release_name: 'Release ${{ github.sha }}'
        draft: false
        prerelease: false

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./html.zip
        asset_name: html.zip
        asset_content_type: application/zip
  
  post-deploy-test:
    runs-on: ubuntu-latest

    needs: deploy

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Test webpage accessibility
      run: |
        urls=(
          "https://21flyers.com/index.htm"
          "https://21flyers.com/Links.html"
          "https://21flyers.com/Library.htm"
          "https://21flyers.com/Join.htm"
          "https://21flyers.com/Announcements.htm"
          "https://21flyers.com/Events.htm"
          "https://21flyers.com/files/21%20Flyers%20Application.pdf"
        )
        for url in "${urls[@]}"; do
          status=$(curl -o /dev/null -s -w "%{http_code}\n" "$url")
          if [ "$status" -ne 200 ]; then
            echo "URL $url returned status code $status" >> errors.txt
          fi
        done
        if [ -f errors.txt ]; then
          cat errors.txt
          exit 1
        fi

    - name: Send email notification if test fails
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.SMTP_SERVER }}
        server_port: 587
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: "21 Flyers - Web Page Accessibility Test Failed"
        body: |
          The following pages did not return a 200 status:
          $(cat errors.txt)
        to: andre.faria.24@gmail.com
        from: andre.faria.24+github@gmail.com