name: Deploy website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create zip file
      run: zip -r www.zip www

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy zip file to EC2
      run: scp -o StrictHostKeyChecking=no www.zip ec2-user@${{ secrets.EC2_PUB_IP }}:/tmp/

    - name: Unzip and deploy files on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUB_IP }} << 'EOF'
          sudo unzip -o /tmp/www.zip -d /usr/share/nginx/html/
          sudo rm /tmp/www.zip
          sudo systemctl restart nginx
        EOF